### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by albertghionea**
https://www.pivotaltracker.com/story/show/133400061

-reorganize styles.css
-slightly reorganized index.html
-took out unnecessary bower components (some elements-bootstrap/fonts/jquery-countdown- still needed)
-took out some javascript files which didn't appear to do anything or im just a peasant
-made changes to 2016.html to reflect the above changes

-Tested locally, looked ok. Please take a look as well, though, since this is the first time I've refactored something.

### CODE REVIEW

**Comment by jack-mo** [comment]
Clicking on a header does not perform a smooth transition to the section. Also, it brings it too low.

**Comment by jack-mo** [comment]
Countdown is missing

**Comment by jack-mo** [comment]
Email link under sponsor list and at bottom of the page is not working.

**Comment by jack-mo** [comment]
🐺

**Comment by timmui** [comment]
Missing padding on the hardware boxes 
image

**Comment by AdrianMachado** [comment]
🐺

**Comment by timmui** [comment]
@albertghionea fix the issue with bootstrap pls

**Comment by timmui** [comment]
See #14

**Pull request closed without merging**
