### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by albertghionea**
idk why but I had git problems trying to push changes into the refactor branch so I created a new branch. invalid src refspec or something, and the solutions I found on Google didn't work.

### CODE REVIEW

**Comment by timmui** [comment]
@albertghionea why are the number of files changed so much smaller?

**Comment by albertghionea** [comment]
@timmui a lot of the bower components are still there. Last time I removed them all (except for logical ones like countdown, fonts etc.) there were still problems. For now, cleaner html/css files, centred <br>s and fewer useless files is a step forward; I can always play around with removing bower components to find out which ones affect things.

**Comment by timmui** [comment]
Okay, sure

**Review by timmui — APPROVED** [review]
LGTM

**Comment by jack-mo** [comment]
LGTM

**Pull request merged**
